import { Team } from "./team.interface";

export interface TeamsList {
    npatriots: Team,
    njets: Team,
    bbills: Team,
    mdolphins: Team,
    bravens: Team,
    cbengals: Team,
    cbrowns: Team,
    psteelers: Team,
    icolts: Team,
    ttitans: Team,
    htexans: Team,
    jjaguars: Team,
    kchiefs: Team,
    dbroncos: Team,
    lraiders: Team,
    lchargers: Team,
    ngiants: Team,
    dcowboys: Team,
    wcommanders: Team,
    peagles: Team,
    dlions: Team,
    gpackers: Team,
    mvikings: Team,
    cbears: Team,
    tbuccaneers: Team,
    nsaints: Team,
    afalcons: Team,
    cpanthers: Team,
    s49: Team,
    sseahawks: Team,
    acardinals: Team,
    lrams: Team
};
