/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Standing } from "./components/ftb-store/interfaces/standing.interface";
import { Team } from "./components/ftb-store/interfaces/team.interface";
import { Match } from "./components/ftb-store/interfaces/match.interface";
import { TeamsList } from "./components/ftb-store/interfaces/teams-list.interface";
export { Standing } from "./components/ftb-store/interfaces/standing.interface";
export { Team } from "./components/ftb-store/interfaces/team.interface";
export { Match } from "./components/ftb-store/interfaces/match.interface";
export { TeamsList } from "./components/ftb-store/interfaces/teams-list.interface";
export namespace Components {
    interface FtbMatch {
    }
    interface FtbScheduleLeague {
    }
    interface FtbScheduleTeam {
        "even": boolean;
        "team": Standing;
    }
    interface FtbSettings {
    }
    interface FtbStandings {
    }
    interface FtbStore {
        "doDummyRun": () => Promise<void>;
        "getScheduleAndTeams": () => Promise<any>;
        "getTeamByCode": (teamCode: string) => Promise<Team>;
        "getWeekMatches": (week: string) => Promise<Array<Match>>;
        "manualDataUpdate": (newTeams: any, newSchedule: any) => Promise<void>;
        "reset": () => Promise<void>;
        "setView": (view: string) => Promise<void>;
        "updateMatch": (week: string, winningTeamCode: string) => Promise<any>;
    }
    interface FtbTeam {
    }
    interface FtbWeek {
        "teams": TeamsList;
        "weekName": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFtbMatchElement extends Components.FtbMatch, HTMLStencilElement {
    }
    var HTMLFtbMatchElement: {
        prototype: HTMLFtbMatchElement;
        new (): HTMLFtbMatchElement;
    };
    interface HTMLFtbScheduleLeagueElement extends Components.FtbScheduleLeague, HTMLStencilElement {
    }
    var HTMLFtbScheduleLeagueElement: {
        prototype: HTMLFtbScheduleLeagueElement;
        new (): HTMLFtbScheduleLeagueElement;
    };
    interface HTMLFtbScheduleTeamElement extends Components.FtbScheduleTeam, HTMLStencilElement {
    }
    var HTMLFtbScheduleTeamElement: {
        prototype: HTMLFtbScheduleTeamElement;
        new (): HTMLFtbScheduleTeamElement;
    };
    interface HTMLFtbSettingsElement extends Components.FtbSettings, HTMLStencilElement {
    }
    var HTMLFtbSettingsElement: {
        prototype: HTMLFtbSettingsElement;
        new (): HTMLFtbSettingsElement;
    };
    interface HTMLFtbStandingsElement extends Components.FtbStandings, HTMLStencilElement {
    }
    var HTMLFtbStandingsElement: {
        prototype: HTMLFtbStandingsElement;
        new (): HTMLFtbStandingsElement;
    };
    interface HTMLFtbStoreElement extends Components.FtbStore, HTMLStencilElement {
    }
    var HTMLFtbStoreElement: {
        prototype: HTMLFtbStoreElement;
        new (): HTMLFtbStoreElement;
    };
    interface HTMLFtbTeamElement extends Components.FtbTeam, HTMLStencilElement {
    }
    var HTMLFtbTeamElement: {
        prototype: HTMLFtbTeamElement;
        new (): HTMLFtbTeamElement;
    };
    interface HTMLFtbWeekElement extends Components.FtbWeek, HTMLStencilElement {
    }
    var HTMLFtbWeekElement: {
        prototype: HTMLFtbWeekElement;
        new (): HTMLFtbWeekElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ftb-match": HTMLFtbMatchElement;
        "ftb-schedule-league": HTMLFtbScheduleLeagueElement;
        "ftb-schedule-team": HTMLFtbScheduleTeamElement;
        "ftb-settings": HTMLFtbSettingsElement;
        "ftb-standings": HTMLFtbStandingsElement;
        "ftb-store": HTMLFtbStoreElement;
        "ftb-team": HTMLFtbTeamElement;
        "ftb-week": HTMLFtbWeekElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FtbMatch {
    }
    interface FtbScheduleLeague {
    }
    interface FtbScheduleTeam {
        "even"?: boolean;
        "team"?: Standing;
    }
    interface FtbSettings {
    }
    interface FtbStandings {
    }
    interface FtbStore {
    }
    interface FtbTeam {
    }
    interface FtbWeek {
        "teams"?: TeamsList;
        "weekName"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ftb-match": FtbMatch;
        "ftb-schedule-league": FtbScheduleLeague;
        "ftb-schedule-team": FtbScheduleTeam;
        "ftb-settings": FtbSettings;
        "ftb-standings": FtbStandings;
        "ftb-store": FtbStore;
        "ftb-team": FtbTeam;
        "ftb-week": FtbWeek;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ftb-match": LocalJSX.FtbMatch & JSXBase.HTMLAttributes<HTMLFtbMatchElement>;
            "ftb-schedule-league": LocalJSX.FtbScheduleLeague & JSXBase.HTMLAttributes<HTMLFtbScheduleLeagueElement>;
            "ftb-schedule-team": LocalJSX.FtbScheduleTeam & JSXBase.HTMLAttributes<HTMLFtbScheduleTeamElement>;
            "ftb-settings": LocalJSX.FtbSettings & JSXBase.HTMLAttributes<HTMLFtbSettingsElement>;
            "ftb-standings": LocalJSX.FtbStandings & JSXBase.HTMLAttributes<HTMLFtbStandingsElement>;
            "ftb-store": LocalJSX.FtbStore & JSXBase.HTMLAttributes<HTMLFtbStoreElement>;
            "ftb-team": LocalJSX.FtbTeam & JSXBase.HTMLAttributes<HTMLFtbTeamElement>;
            "ftb-week": LocalJSX.FtbWeek & JSXBase.HTMLAttributes<HTMLFtbWeekElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
